
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-dep
  name: nginx-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-dep
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 80
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: nginx-vol
      volumes:
      - name: nginx-vol
        configMap: 
          name: nginx-configmap

status: {}