apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        location / {
          proxy_pass http://nextjs-service:3000;
          proxy_redirect                          off;
          proxy_set_header Host                   $host;
          proxy_set_header X-Real-IP              $remote_addr;
          proxy_set_header X-Forwarded-Host       $host;
          proxy_set_header X-Forwarded-Server     $host;
          proxy_set_header X-Forwarded-Proto      $scheme;
          proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        }
        # error_page   500 502 503 504  /50x.html;
        # location = /50x.html {
        #     root   /usr/share/nginx/html;
        # }
    }
---