apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-nodeport
  name: nginx-nodeport
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx-dep
  type: NodePort
status:
  loadBalancer: {}